#!/bin/sh

# Quick and dirty output for now.  This doesn't really serve the
# needs of comparative analysis, it just shows the raw data.

for name in `git ls-files data`; do
  echo "*** ${name}"
  echo ""
  head -1 ${name}
  echo ""
  ./readability-indicators < ${name}
  echo ""
done

# To process a set of specific speeches, try something like this:
# 
#   $ for name in data/2021-*txt; do echo "*** ${name} *** "; echo -n "    "; head -1 ${name}; echo ""; cat ${name} | ./readability-indicators; echo ""; done
